-- MySQL Script generated by MySQL Workbench
-- Tue 11 Sep 2018 05:00:46 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema teststudent
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `teststudent` ;

-- -----------------------------------------------------
-- Schema teststudent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `teststudent` DEFAULT CHARACTER SET utf8 ;
USE `teststudent` ;

-- -----------------------------------------------------
-- Table `teststudent`.`korisnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teststudent`.`korisnik` ;

CREATE TABLE IF NOT EXISTS `teststudent`.`korisnik` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `ime` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `prezime` VARCHAR(255) NOT NULL,
  `tip` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_87tbhltaua2a6k6jrdfl1kqap` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teststudent`.`predmet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teststudent`.`predmet` ;

CREATE TABLE IF NOT EXISTS `teststudent`.`predmet` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(255) NOT NULL,
  `sifra` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_pwqsanb5gh8ny770ng22d0fnm` (`sifra` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teststudent`.`kurs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teststudent`.`kurs` ;

CREATE TABLE IF NOT EXISTS `teststudent`.`kurs` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_pred` BIGINT(20) NOT NULL,
  `kraj` DATE NOT NULL,
  `pocetak` DATE NOT NULL,
  `sifra` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_9u2fo3xw8eqa36yio0m3rkl40` (`sifra` ASC),
  INDEX `fk_kurs_predmet1_idx` (`id_pred` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teststudent`.`test`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teststudent`.`test` ;

CREATE TABLE IF NOT EXISTS `teststudent`.`test` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_prof` BIGINT(20) NOT NULL,
  `id_kurs` BIGINT(20) NOT NULL,
  `datum` DATETIME NOT NULL,
  `mqtt_tema_o` VARCHAR(255) NOT NULL,
  `mqtt_tema_p` VARCHAR(255) NOT NULL,
  `naziv_testa` VARCHAR(255) NOT NULL,
  `sala` VARCHAR(255) NOT NULL,
  `zavrsen` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_ao3y83a385wca4ybor4s0aba2` (`mqtt_tema_o` ASC),
  UNIQUE INDEX `UK_92ux337hk8h2qttkqteuwcuql` (`mqtt_tema_p` ASC),
  INDEX `fk_test_korisnik1_idx` (`id_prof` ASC),
  INDEX `fk_test_kurs1_idx` (`id_kurs` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teststudent`.`pitanje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teststudent`.`pitanje` ;

CREATE TABLE IF NOT EXISTS `teststudent`.`pitanje` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_test` BIGINT(20) NOT NULL,
  `pitanje` VARCHAR(2048) NOT NULL,
  `poslato` TINYINT(1) NOT NULL,
  `tip` VARCHAR(255) NOT NULL,
  `zavrseno` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pitanje_test1_idx` (`id_test` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teststudent`.`ponudjeni_odgovor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teststudent`.`ponudjeni_odgovor` ;

CREATE TABLE IF NOT EXISTS `teststudent`.`ponudjeni_odgovor` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `id_pitanje` BIGINT(20) NOT NULL,
  `odgovor` VARCHAR(2048) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ponudjeni_odgovor_pitanje1_idx` (`id_pitanje` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teststudent`.`odgovor_studenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teststudent`.`odgovor_studenta` ;

CREATE TABLE IF NOT EXISTS `teststudent`.`odgovor_studenta` (
  `id_student` BIGINT(20) NOT NULL,
  `id_pitanje` BIGINT(20) NOT NULL,
  `id_ponudjen_odg` BIGINT(20) NULL,
  `odgovor_stud` VARCHAR(2048) NULL DEFAULT NULL,
  PRIMARY KEY (`id_student`, `id_pitanje`),
  INDEX `fk_odgovor_studenta_korisnik1_idx` (`id_student` ASC),
  INDEX `fk_odgovor_studenta_pitanje1_idx` (`id_pitanje` ASC),
  INDEX `fk_odgovor_studenta_ponudjeni_odgovor1_idx` (`id_ponudjen_odg` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teststudent`.`pohadja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teststudent`.`pohadja` ;

CREATE TABLE IF NOT EXISTS `teststudent`.`pohadja` (
  `id_student` BIGINT(20) NOT NULL,
  `id_kurs` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_kurs`, `id_student`),
  INDEX `fk_pohadja_korisnik1_idx` (`id_student` ASC),
  INDEX `fk_pohadja_kurs1_idx` (`id_kurs` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `teststudent`.`prisustvo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `teststudent`.`prisustvo` ;

CREATE TABLE IF NOT EXISTS `teststudent`.`prisustvo` (
  `id_test` BIGINT(20) NOT NULL,
  `id_student` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id_test`, `id_student`),
  INDEX `fk_prisustvo_test1_idx` (`id_test` ASC),
  INDEX `fk_prisustvo_korisnik1_idx` (`id_student` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
